/* Piper generated audio map — do not edit manually. */
const KP_GENERATED_AUDIO = {
  "letterName": {
    "a": "assets/audio/letter-names/a.wav",
    "b": "assets/audio/letter-names/b.wav",
    "c": "assets/audio/letter-names/c.wav",
    "d": "assets/audio/letter-names/d.wav",
    "e": "assets/audio/letter-names/e.wav",
    "f": "assets/audio/letter-names/f.wav",
    "g": "assets/audio/letter-names/g.wav",
    "h": "assets/audio/letter-names/h.wav",
    "i": "assets/audio/letter-names/i.wav",
    "j": "assets/audio/letter-names/j.wav",
    "k": "assets/audio/letter-names/k.wav",
    "l": "assets/audio/letter-names/l.wav",
    "m": "assets/audio/letter-names/m.wav",
    "n": "assets/audio/letter-names/n.wav",
    "o": "assets/audio/letter-names/o.wav",
    "p": "assets/audio/letter-names/p.wav",
    "q": "assets/audio/letter-names/q.wav",
    "r": "assets/audio/letter-names/r.wav",
    "s": "assets/audio/letter-names/s.wav",
    "t": "assets/audio/letter-names/t.wav",
    "u": "assets/audio/letter-names/u.wav",
    "v": "assets/audio/letter-names/v.wav",
    "w": "assets/audio/letter-names/w.wav",
    "x": "assets/audio/letter-names/x.wav",
    "y": "assets/audio/letter-names/y.wav",
    "z": "assets/audio/letter-names/z.wav"
  },
  "word": {
    "a": "assets/audio/words/a.wav",
    "a cat": "assets/audio/words/a-cat.wav",
    "a map": "assets/audio/words/a-map.wav",
    "a pin": "assets/audio/words/a-pin.wav",
    "am": "assets/audio/words/am.wav",
    "an": "assets/audio/words/an.wav",
    "apple": "assets/audio/words/apple.wav",
    "at": "assets/audio/words/at.wav",
    "bag": "assets/audio/words/bag.wav",
    "ball": "assets/audio/words/ball.wav",
    "bat": "assets/audio/words/bat.wav",
    "bed": "assets/audio/words/bed.wav",
    "big": "assets/audio/words/big.wav",
    "box": "assets/audio/words/box.wav",
    "bug": "assets/audio/words/bug.wav",
    "bus": "assets/audio/words/bus.wav",
    "cake": "assets/audio/words/cake.wav",
    "can": "assets/audio/words/can.wav",
    "cap": "assets/audio/words/cap.wav",
    "cape": "assets/audio/words/cape.wav",
    "cat": "assets/audio/words/cat.wav",
    "cod": "assets/audio/words/cod.wav",
    "cop": "assets/audio/words/cop.wav",
    "cot": "assets/audio/words/cot.wav",
    "cub": "assets/audio/words/cub.wav",
    "cube": "assets/audio/words/cube.wav",
    "cup": "assets/audio/words/cup.wav",
    "cut": "assets/audio/words/cut.wav",
    "dad": "assets/audio/words/dad.wav",
    "dig": "assets/audio/words/dig.wav",
    "dip": "assets/audio/words/dip.wav",
    "dot": "assets/audio/words/dot.wav",
    "duck": "assets/audio/words/duck.wav",
    "egg": "assets/audio/words/egg.wav",
    "fan": "assets/audio/words/fan.wav",
    "fish": "assets/audio/words/fish.wav",
    "fit": "assets/audio/words/fit.wav",
    "fun": "assets/audio/words/fun.wav",
    "gap": "assets/audio/words/gap.wav",
    "gas": "assets/audio/words/gas.wav",
    "goat": "assets/audio/words/goat.wav",
    "got": "assets/audio/words/got.wav",
    "ham": "assets/audio/words/ham.wav",
    "has": "assets/audio/words/has.wav",
    "hat": "assets/audio/words/hat.wav",
    "hen": "assets/audio/words/hen.wav",
    "hop": "assets/audio/words/hop.wav",
    "hot": "assets/audio/words/hot.wav",
    "hug": "assets/audio/words/hug.wav",
    "hut": "assets/audio/words/hut.wav",
    "i": "assets/audio/words/i.wav",
    "in": "assets/audio/words/in.wav",
    "ink": "assets/audio/words/ink.wav",
    "it": "assets/audio/words/it.wav",
    "jet": "assets/audio/words/jet.wav",
    "king": "assets/audio/words/king.wav",
    "leg": "assets/audio/words/leg.wav",
    "like": "assets/audio/words/like.wav",
    "lion": "assets/audio/words/lion.wav",
    "lip": "assets/audio/words/lip.wav",
    "mad": "assets/audio/words/mad.wav",
    "man": "assets/audio/words/man.wav",
    "map": "assets/audio/words/map.wav",
    "mat": "assets/audio/words/mat.wav",
    "moon": "assets/audio/words/moon.wav",
    "mop": "assets/audio/words/mop.wav",
    "nap": "assets/audio/words/nap.wav",
    "net": "assets/audio/words/net.wav",
    "nod": "assets/audio/words/nod.wav",
    "not": "assets/audio/words/not.wav",
    "octopus": "assets/audio/words/octopus.wav",
    "pad": "assets/audio/words/pad.wav",
    "pan": "assets/audio/words/pan.wav",
    "pat": "assets/audio/words/pat.wav",
    "pen": "assets/audio/words/pen.wav",
    "pet": "assets/audio/words/pet.wav",
    "pig": "assets/audio/words/pig.wav",
    "pin": "assets/audio/words/pin.wav",
    "pine": "assets/audio/words/pine.wav",
    "pot": "assets/audio/words/pot.wav",
    "queen": "assets/audio/words/queen.wav",
    "rain": "assets/audio/words/rain.wav",
    "red": "assets/audio/words/red.wav",
    "rub": "assets/audio/words/rub.wav",
    "run": "assets/audio/words/run.wav",
    "sad": "assets/audio/words/sad.wav",
    "sat": "assets/audio/words/sat.wav",
    "see": "assets/audio/words/see.wav",
    "sip": "assets/audio/words/sip.wav",
    "sit": "assets/audio/words/sit.wav",
    "sun": "assets/audio/words/sun.wav",
    "tag": "assets/audio/words/tag.wav",
    "tap": "assets/audio/words/tap.wav",
    "tape": "assets/audio/words/tape.wav",
    "ten": "assets/audio/words/ten.wav",
    "the": "assets/audio/words/the.wav",
    "tiger": "assets/audio/words/tiger.wav",
    "tip": "assets/audio/words/tip.wav",
    "top": "assets/audio/words/top.wav",
    "tub": "assets/audio/words/tub.wav",
    "umbrella": "assets/audio/words/umbrella.wav",
    "van": "assets/audio/words/van.wav",
    "web": "assets/audio/words/web.wav",
    "yo-yo": "assets/audio/words/yo-yo.wav",
    "zebra": "assets/audio/words/zebra.wav"
  },
  "sentence": {
    "a cat can sit.": "assets/audio/sentences/a-cat-can-sit.wav",
    "ben can run.": "assets/audio/sentences/ben-can-run.wav",
    "cat can sit.": "assets/audio/sentences/cat-can-sit.wav",
    "dad got it.": "assets/audio/sentences/dad-got-it.wav",
    "dan can dig.": "assets/audio/sentences/dan-can-dig.wav",
    "hug ben, dad.": "assets/audio/sentences/hug-ben-dad.wav",
    "i can run.": "assets/audio/sentences/i-can-run.wav",
    "i have a box.": "assets/audio/sentences/i-have-a-box.wav",
    "i have a hat.": "assets/audio/sentences/i-have-a-hat.wav",
    "i have a net.": "assets/audio/sentences/i-have-a-net.wav",
    "i have a yo-yo.": "assets/audio/sentences/i-have-a-yo-yo.wav",
    "i have an umbrella.": "assets/audio/sentences/i-have-an-umbrella.wav",
    "i kick a ball.": "assets/audio/sentences/i-kick-a-ball.wav",
    "i like": "assets/audio/sentences/i-like.wav",
    "i like apples.": "assets/audio/sentences/i-like-apples.wav",
    "i like the big pig.": "assets/audio/sentences/i-like-the-big-pig.wav",
    "i like the rain.": "assets/audio/sentences/i-like-the-rain.wav",
    "i like the sun.": "assets/audio/sentences/i-like-the-sun.wav",
    "i see a cat.": "assets/audio/sentences/i-see-a-cat.wav",
    "i see a fish.": "assets/audio/sentences/i-see-a-fish.wav",
    "i see a king.": "assets/audio/sentences/i-see-a-king.wav",
    "i see a pig.": "assets/audio/sentences/i-see-a-pig.wav",
    "i see a queen.": "assets/audio/sentences/i-see-a-queen.wav",
    "i see a van.": "assets/audio/sentences/i-see-a-van.wav",
    "i see a web.": "assets/audio/sentences/i-see-a-web.wav",
    "i see a zebra.": "assets/audio/sentences/i-see-a-zebra.wav",
    "i see an egg.": "assets/audio/sentences/i-see-an-egg.wav",
    "i see an octopus.": "assets/audio/sentences/i-see-an-octopus.wav",
    "i see the moon.": "assets/audio/sentences/i-see-the-moon.wav",
    "pam, tap it.": "assets/audio/sentences/pam-tap-it.wav",
    "sam had fun.": "assets/audio/sentences/sam-had-fun.wav",
    "sam sat.": "assets/audio/sentences/sam-sat.wav",
    "the big pig": "assets/audio/sentences/the-big-pig.wav",
    "the big pig has": "assets/audio/sentences/the-big-pig-has.wav",
    "the big pig has a map.": "assets/audio/sentences/the-big-pig-has-a-map.wav",
    "the duck can swim.": "assets/audio/sentences/the-duck-can-swim.wav",
    "the goat can jump.": "assets/audio/sentences/the-goat-can-jump.wav",
    "the ink is black.": "assets/audio/sentences/the-ink-is-black.wav",
    "the jet is fast.": "assets/audio/sentences/the-jet-is-fast.wav",
    "the lion can run.": "assets/audio/sentences/the-lion-can-run.wav",
    "the pig": "assets/audio/sentences/the-pig.wav",
    "the pig can": "assets/audio/sentences/the-pig-can.wav",
    "the pig can hop.": "assets/audio/sentences/the-pig-can-hop.wav",
    "the red hen ran.": "assets/audio/sentences/the-red-hen-ran.wav",
    "the tiger can run.": "assets/audio/sentences/the-tiger-can-run.wav",
    "tim, sit.": "assets/audio/sentences/tim-sit.wav",
    "what can the pig do?": "assets/audio/sentences/what-can-the-pig-do.wav",
    "what does the pig have?": "assets/audio/sentences/what-does-the-pig-have.wav"
  }
};
